"use client";

import { motion } from "framer-motion";
import { Globe2, Bot, Sparkles } from "lucide-react";

export function GEOSection() {
  return (
    <section className="relative overflow-hidden border-t border-white/10 bg-black px-6 py-24 text-white md:px-12 lg:px-20">

      {/* Background Glow */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute right-0 top-0 h-[350px] w-[350px] rounded-full bg-purple-500/10 blur-3xl" />
      </div>

      <div className="mx-auto max-w-7xl">

        {/* Heading */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          viewport={{ once: true }}
          className="max-w-4xl"
        >
          <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-purple-400 backdrop-blur-xl">
            <Sparkles className="h-4 w-4" />
            Generative Engine Optimization
          </div>

          <h2 className="text-4xl font-bold leading-tight md:text-5xl">
            What is{" "}
            <span className="bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent">
              GEO?
            </span>
          </h2>

          <p className="mt-8 text-lg leading-relaxed text-white/70">
            Generative Engine Optimization (GEO) focuses on improving
            your visibility inside AI-generated responses. GEO helps
            businesses appear in AI answers generated by platforms like
            ChatGPT, Gemini, Perplexity, and Google AI Overviews.
          </p>
        </motion.div>

        {/* Cards */}
        <div className="mt-16 grid gap-6 md:grid-cols-3">

          {[
            {
              icon: Bot,
              title: "AI Answer Visibility",
              description:
                "Appear inside AI-generated answers across modern search platforms.",
            },
            {
              icon: Globe2,
              title: "Entity Optimization",
              description:
                "Build semantic relevance so AI systems understand your brand and expertise.",
            },
            {
              icon: Sparkles,
              title: "Future Search Ready",
              description:
                "Prepare your website for the next generation of AI-driven discovery.",
            },
          ].map((item, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
              className="rounded-3xl border border-white/10 bg-white/5 p-8 backdrop-blur-xl transition-all duration-300 hover:border-purple-400/30 hover:bg-white/10"
            >
              <item.icon className="mb-5 h-10 w-10 text-purple-400" />

              <h3 className="text-2xl font-semibold">
                {item.title}
              </h3>

              <p className="mt-4 leading-relaxed text-white/70">
                {item.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}